-- Knowledge Browser schema: short_id, content_md, content_version for hierarchy tables
-- short_id: 8-char Base62, globally unique, generated by scripts/generate-short-ids.js
-- content_md: versioned markdown content for knowledge browser display
-- content_version: integer version counter, incremented on each content_md change

-- Missions
ALTER TABLE missions ADD COLUMN short_id TEXT;
ALTER TABLE missions ADD COLUMN content_md TEXT;
ALTER TABLE missions ADD COLUMN content_version INTEGER DEFAULT 0;

-- Capabilities
ALTER TABLE capabilities ADD COLUMN short_id TEXT;
ALTER TABLE capabilities ADD COLUMN content_md TEXT;
ALTER TABLE capabilities ADD COLUMN content_version INTEGER DEFAULT 0;

-- Requirements
ALTER TABLE requirements ADD COLUMN short_id TEXT;
ALTER TABLE requirements ADD COLUMN content_md TEXT;
ALTER TABLE requirements ADD COLUMN content_version INTEGER DEFAULT 0;

-- Unique indexes on short_id (SQLite cannot add UNIQUE constraint via ALTER TABLE)
CREATE UNIQUE INDEX IF NOT EXISTS idx_missions_short_id ON missions(short_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_capabilities_short_id ON capabilities(short_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_requirements_short_id ON requirements(short_id);

-- Content history: append-only audit trail
CREATE TABLE IF NOT EXISTS node_content_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  node_id TEXT NOT NULL,
  node_type TEXT NOT NULL CHECK(node_type IN ('mission', 'capability', 'requirement')),
  version INTEGER NOT NULL,
  content_md TEXT NOT NULL,
  changed_by TEXT NOT NULL,
  changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_content_history_node ON node_content_history(node_id, node_type);

-- Generate short_ids for existing nodes using hex(randomblob(4)) = 8 hex chars
-- Idempotent: only sets WHERE short_id IS NULL
UPDATE missions SET short_id = lower(hex(randomblob(4))) WHERE short_id IS NULL;
UPDATE capabilities SET short_id = lower(hex(randomblob(4))) WHERE short_id IS NULL;
UPDATE requirements SET short_id = lower(hex(randomblob(4))) WHERE short_id IS NULL;
